Fix (searchFn)[#101] searchFn callback should only call once when typing in the search bar
sanusart/react-dropdown-select pull request #131
Opened 2020-10-18 23:38 UTC by pattiereaves

- Add searchResults array to the component state so that we can store the calculation and prevent it from being executed multiple times.
- Adds example documentation for how to add a custom searchFn.

resolves #101

2020-10-19 01:38 UTC, pattiereaves commented
Would you be willing to [add the hacktoberfest label](https://hacktoberfest.digitalocean.com/faq) to this project?

2020-10-19 20:01 UTC, sanusart requested changes

2020-10-19 20:01 UTC, sanusart commented on src/index.js
> +    console.log({ event });
Not needed anymore I believe.

2020-10-20 04:41 UTC, sanusart approved these changes
@pattiereaves thank you!

2020-10-20 04:46 UTC, merged